-- phpMyAdmin SQL Dump
-- version 3.5.2.2
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Dec 13, 2013 at 01:31 PM
-- Server version: 5.5.27
-- PHP Version: 5.4.7

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `spacexstats`
--

-- --------------------------------------------------------

--
-- Table structure for table `missions`
--

CREATE TABLE IF NOT EXISTS `missions` (
  `mission_id` int(10) NOT NULL AUTO_INCREMENT,
  `launch_date_time` datetime DEFAULT NULL,
  `expected_launch` varchar(50) CHARACTER SET latin1 DEFAULT NULL,
  `payload` varchar(100) CHARACTER SET latin1 NOT NULL,
  `dragon_duration` int(10) DEFAULT NULL,
  `dragon_up_mass` int(10) DEFAULT NULL,
  `dragon_down_mass` int(10) DEFAULT NULL,
  `astronauts` int(11) NOT NULL,
  `primary_satellites` int(11) NOT NULL,
  `total_satellites` int(11) NOT NULL,
  `destination` varchar(10) CHARACTER SET latin1 NOT NULL,
  `vehicle` varchar(50) CHARACTER SET latin1 NOT NULL,
  `core` varchar(10) CHARACTER SET latin1 NOT NULL,
  `launch_site` varchar(50) CHARACTER SET latin1 NOT NULL,
  `summary` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `article` text COLLATE utf8_unicode_ci NOT NULL,
  `complete` tinyint(1) NOT NULL,
  `in_progress` tinyint(1) NOT NULL,
  `success` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`mission_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=24 ;

--
-- Dumping data for table `missions`
--

INSERT INTO `missions` (`mission_id`, `launch_date_time`, `expected_launch`, `payload`, `dragon_duration`, `dragon_up_mass`, `dragon_down_mass`, `astronauts`, `primary_satellites`, `total_satellites`, `destination`, `vehicle`, `core`, `launch_site`, `summary`, `article`, `complete`, `in_progress`, `success`) VALUES
(1, '2006-03-24 22:30:00', NULL, 'FalconSAT-2', NULL, NULL, NULL, 0, 0, 1, 'LEO', 'Falcon 1', 'F1-001', 'Omelek Island, Kwajalein', 'SpaceX''s first launch, which ended in disaster 25 seconds after launch due to an engine issue.\n', '<p><img src="/articleimg/f1f1.jpg" />This was SpaceX''s first launch, of any rocket, and the first attempt at a private-funded and developed rocket to reach Earth orbit. Getting to launch took over 4 years, and was marked with numerous delays. Originally scheduled to be launched on the 100th anniversary of the Wright Brother''s historic flight, on 17 December 2003 from Vandenberg Air Force Base, eventually, Falcon 1 rose off the pad from Omelek Island in Kwajalein Atoll over 2 years later on 24 March 2006. The change in launch site as caused by scheduling conflicts and an unwillingness by other Vandenberg members to host experimental rocket launches.</p>\n\n<p>Falcon 1 was a small rocket. Fueled by RP-1 and Liquid Oxygen, it only had the ability to place 670kg into Low Earth Orbit, yet at a cost of $7 million per launch, was much cheaper than competitor offerings. It''s first flight was to carry the FalconSAT-2 satellite, built by the United States Air Force Academy.</p> \n\n<p>Liftoff occurred at 2230 UTC, and appeared to proceed nominally until T+25 seconds, when the rocket pitched over and control was lost. The launch was filmed from at least three locations, on the rocket itself, on a ground camera pointing at the pad, and remotely off-island from a large distance away - only the onboard rocket camera shows the ground impact. All three of these videos have credit given to Branden Spikes, who was Chief Information Officer of SpaceX at the time. Impact occurred at T+41s  when the rocket smashed into a shallow, dead reef on the ocean side of Omelek Island about 80 metres from the launch pad. </p>\n\n<p>"I spent the day picking up rocket pieces from the reef, which sucked." - Elon Musk.</p>\n\n<p>Amazingly, the satellite was blown free from the rocket, and was discovered in a storage shed (albeit damaged) a few metres away from the shipping container than had been used to send it from Colorado to the launch site. The failure was originally attributed to an improperly tightened nut on the first stage engine, but later evidence showed the nut had failed due to corrosion from Kwajalein''s intense oceanic environment. </p>\n', 1, 0, 0),
(2, '2007-03-21 01:10:00', NULL, 'DemoSat', NULL, NULL, NULL, 0, 0, 0, 'LEO', 'Falcon 1', 'F1-002', 'Omelek Island, Kwajalein', 'The second launch of Falcon 1, attempted (and failed to) carry a mass simulator into orbit. ', '<p><img src="/articleimg/omelekf2.jpg" />SpaceX''s second launch of Falcon 1 occurred nearly 1 year after the first spectacular failure where Falcon 1 ended up disintegrating on a nearby reef. Again launched from Omelek Island in Kwajalein Atoll after numerous delays involving computer issues and scheduling conflicts with a Minuteman III test flight which would re-enter of Kwajalein, the second flight of Falcon 1 was much more successful than the first flight which ended shortly after launch, yet also failed to deliver its payload simulator into Earth orbit. </p> \n\n<p>The first stage performed well, and stage separation occurred, yet the interstage bumped the second stage engine nozzle due to higher than expected rotation rates on the rocket, which in turn was caused by an incorrect propellant utilization file being loaded into the engine computer which resulted in slightly lower thrust causing the rocket to be travelling slower and lower than predicted - the additional aerodynamic forces at stage separation imparted more force than they normally would have had the rocket been at the correct altitude, causing the higher-than-expected rotation. Nonetheless, the vehicle performance was within acceptable limits until T+4 minutes 25 seconds. </p>\n\n<p>At this point, a circular corkscrew oscillation began than increased in amplitude until video was lost and the vehicle started to roll at T+5:01, eventually exceeding the capacity of the roll control thrusters to null out the rotation. Finally, the fuel in the tank centrifuged and at T+7:30 the second engine shut down due to flame out. All evidence points to the excess roll being caused by Liquid Oxygen sloshing in the tank - baffles were added in future flights to address this. </p>\n\n<p>Falcon 1 eventually coasted to an altitude of 289km with a final velocity of 5.1km/s, short of the 7.5km/s needed to achieve orbit. Regardless, flight 2 was declared a partial success as it flight tested 95% of the rockets componentry.</p>\n', 1, 0, 0),
(3, '2008-08-03 03:34:00', NULL, 'Falcon 1 Flight 3', NULL, NULL, NULL, 0, 0, 4, 'LEO', 'Falcon 1', 'F1-003', 'Omelek Island, Kwajalein', 'Flight 3 of Falcon 1 was to place a quadro of small satellites into Earth orbit, but again failed. ', '<p><img src="/articleimg/falcon1flight3.jpg" />Falcon 1 Flight 3 took off from Omelek Island on Kwajalein in August 2008, nearly one and a half years after the second failed attempt of Falcon 1. Unlike flight 2, flight 3 carried a myriad of 4 small satellites: Trailblazer for the U.S. Air Force; the 4kg satellite NanoSail-D which had an solar sail area of 10 square metres; the breadloaf sized PRESat, which was to study yeast in a controlled environment in micro-gravity, and a orbital burial capsule for Celestis.</p>\n\n<p>Flight 3 of Falcon 1 was the first to feature the all new more powerful Merlin 1C engine which would go on to power the first five Falcon 9 launches and generate a thrust of 480kN in a vacuum with a vacuum specific impulse of 304.8 seconds, and an extended body to accommodate extra propellant.</p> \n\n<p>Liftoff occurred at 3:34 UTC on the 3rd of August after 2 recycle attempts, and the new Merlin 1C engine performed perfectly. Taking in a wealth of improvements that were made after the second flight, the flight went well until at stage separation, some residual fuel in the new Merlin 1C engine evaporated, providing enough transient thrust for the first stage to recontact the second stage, which prevented successful mission completion resulting in all payloads being lost. This seemingly laughable mistake was discovered in a matter of hours and deemed fixable by simply increasing the duration between first stage shutdown and stage separation - one line of code.</p> \n\n<p>At this point, SpaceX was near bankruptcy, and barely had the funds to make a fourth flight. After the failure of the flight, Elon Musk walked out and addressed the company, revealing that funding had been secured for another 2 launches if needed, and that SpaceX would pick itself back up. It did.</p> \n', 1, 0, 0),
(4, '2008-09-28 23:15:00', NULL, 'RatSat', NULL, NULL, NULL, 0, 0, 0, 'LEO', 'Falcon 1', 'F1-004', 'Omelek Island, Kwajalein', 'The first privately-developed liquid fueled rocket to reach orbit.', '<p><img src="/articleimg/f1f4.jpg" />Carrying another mass simulator - this time weighing 165kg and nicknamed "RatSat", Falcon 1 for the first time achieved mission success and became the first privately developed liquid-fueled rocket to reach orbit on 28 September 2008. Test firing occurred on 20 September, and over the next 8 days some changes were made to a pipeline supplying the second stage Kestrel engine with liquid Oxygen.</p>\n\n<p>Liftoff occurred 15 minutes into a 5 hour launch window. At T+9:31, the second stage engine shut down after reaching orbit, something all 3 Falcon 1 flights prior had failed to accomplish. The initial orbit from this burn was 330x650km. After a short coast period, the second engine of Falcon 1 restarted, and performed a second successful burn placing the mass simulator in a 621x643km orbit with an inclination of 9.35 degrees.  </p>\n\n<p>Although original plans for the Falcon 1 were for the first stage to deploy a parachute and splashdown downrange from the launch site to be recovered and reused, no flight succeeded in doing so. Stage recovery was a secondary goal however and not required for mission success. </p>\n\n<p>Elon Musk, the company''s founder and CEO, called the launch a "great day for SpaceX" as he addressed the then 500-employee company.</p>\n\n<p>"The data shows we achieved a super precise orbit insertion--middle of the bull''s eye--and then went on to coast and restart the second stage, which was icing on the cake." ... "This is one of the best days of my life."</p>\n\n<p>The next day after completing this historic spaceflight achievement, NASA phoned, with a nearly $2 billion International Space Station resupply contract. "I couldn''t even be professional" with them on the phone, Musk said. "I told them, ''I love you.''"</p>\n', 1, 0, 1),
(5, '2009-07-14 03:35:00', NULL, 'RazakSAT', NULL, NULL, NULL, 0, 0, 1, 'LEO', 'Falcon 1', 'F1-005', 'Omelek Island, Kwajalein', 'Final launch of Falcon 1 and SpaceX''s second successful flight and first satellite in orbit. ', '<p><img src="/articleimg/f1f5.jpg" />Flight 5 delivered SpaceX''s only successful commercial payload into orbit, the 180kg RazakSat satellite for the Malaysian government. The uphill journey proceeded smoothly with no problems reported after a liftoff at 3:35UTC on 14 July 2009 in what was a relatively uneventful flight which was delayed twice, due to stormy weather and an equipment malfunction. Roughly 10 minutes are liftoff, the second stage shutdown, and the Earth observing satellite entered orbit. </p>\n\n<p>This marked the last flight for Falcon 1, which first flew in 2006. Only the final 2 missions were successful, with the prior 3 all failing to reach Earth orbit. Initially, an enhanced variant of Falcon 1 was to be its replacement. Named Falcon 1e, it was to be a stretched version with more powerful engines - including a modified upper stage engine named Kestrel 2, and wider payload fairing that would carry 1 ton into Low Earth Orbit for $12 million. </p> \n\n<p>SpaceX however had shifted focus to fulfilling its NASA Commercial Orbital Transportation Services obligations and so development of Dragon and the much more powerful Falcon 9 were now priority. In doing so, Falcon 1e was put on hold, and as of 2012 "Current plans are for payloads that would fly on Falcon 1 to be served by flights on the Falcon 9, utilizing excess capacity".</p> \n\n<p>Ultimately, Falcon 1 give SpaceX crucial insight and understanding into the process of developing rockets, and remains to date one of only three rockets designed completely in the 21st century, along with Falcon 9 and Falcon Heavy. </p> \n', 1, 0, 1),
(6, '2010-06-04 18:45:00', NULL, 'Dragon Spacecraft Qualification Unit', NULL, NULL, NULL, 0, 0, 0, 'LEO', 'Falcon 9', 'F9-001', 'Florida SLC-40', 'First launch of the new Falcon 9 from Cape Canaveral delivering the Dragon Spacecraft Qualification Unit into orbit.', '<p><img src="/articleimg/dsqu.jpg" />With Falcon 1 development suspended, Falcon 9 & the Dragon spacecraft became SpaceX''s primary focus in 2009. Falcon 9 features 9 Merlin 1C engines arranged in a 3x3 grid (now replaced with the more efficient ''octaweb''), because "[at the time] we didn''t know what we were doing". The maiden launch of the 333 ton Falcon 9 was a complete success, bar the vehicle experiencing "a little bit of roll at liftoff" - which stopped by the time the rocket had cleared the tower. This was the launch of the Dragon Spacecraft Qualification Unit, and while it was not a functional Dragon spacecraft, this launch still resulted in many firsts apart from the rocket itself. This was the first liftoff of a SpaceX vehicle from the continental United States and (obviously therefore) the first launch of a SpaceX vehicle from Cape Canaveral, Florida. </p>\n\n<p>Before the launch, Musk was quoted as saying "Given that this is a test flight, whatever percentage of getting to orbit we achieve would still be considered a good day. If just the first stage functions correctly, it''s a good day. It''s a great day if both stages function." </p>\n<p>Falcon 9 started its historic uphill journey on 4 June 2010 at 1845 UTC, and entered a 250km orbit a few minutes later. After stage separation, the first stage was destroyed on impact when it hit the Atlantic Ocean after its parachutes failed to deploy. After launch, the onboard batteries failed (as expected) and contact with the spacecraft was lost. The qualification unit was left by SpaceX in Low Earth Orbit, were it completed 300 laps around Earth before re-entering in the early morning hours (UTC) on 27 June, 2010, likely over Syria or Iraq. </p>  \n\n<p>The mission was declared a complete success, and paved the way for SpaceX to start fulfilling its Commercial Orbital Transportation Services contract to enable Dragon to resupply the International Space Station. </p>   \n', 1, 0, 1),
(7, '2010-12-08 15:43:00', NULL, 'COTS Demo 1', 11992, NULL, NULL, 0, 0, 8, 'LEO', 'Falcon 9 + Dragon', 'F9-002', 'Florida SLC-40', 'Second launch of Falcon 9, and first launch of Dragon spacecraft into Low Earth Orbit.', '<p><img src="/articleimg/cots1.jpg" />Less than 6 months after the first launch of Falcon 9, the second core, F9-002, thundered off Space Launch Complex 40 at Cape Canaveral on 8 December 2010, lifting the first operational Dragon spacecraft into orbit for 3 hours. Dragon''s goals for COTS Demo 1 were an in-orbit checkout of the spacecraft''s systems and to successfully reenter, which it did 3 hours 19 minutes and 52 seconds later after two orbits around the Earth in the Pacific Ocean off the coast of California under its trio of white and red Apollo-esque parachutes - the first privately developed spacecraft to orbit Earth and then re-enter. All objectives of the mission were met, which cleared SpaceX to begin the next mission, COTS 2+, which involved rendezvous maneuvers and a berthing with the ISS. </p>   \n\n<p>The mission was picture perfect: "It''s actually almost too good," Mr. Musk said. "We didn''t have to go to backup systems at any point. I''m sort of in semishock." The flight proceeded despite several cracks being noticed in the outer portions of the Niobium skirt of the second stage engine. The solution was to trim the un-needed four feet off of the nozzle just a few days before launch, as the resulting performance loss was not critical. </p>   \n\n<p>Less reported on was the deployment of 8 additional secondary satellites which separated from Dragon and the upper stage once in orbit - a numerical SpaceX record that remains to date. These included SMDC-ONE 1, QbX 1 & 2, Mayflower-Caerus, and Perseus 000-003. </p>   \n\n<p>In addition to the 8 other secondary satellites, stowed away aboard the spacecraft was a secret payload which wasn''t revealed until after the mission splashed down. Musk was noticeably secretive, "It''s kind of funny, If you like Monty Python, you''ll love the secret". The secret was later revealed to be a large wheel of cheese - complete with the words "Top Secret!" emblazoned on the cover. </p>   \n', 1, 0, 1),
(8, '2012-05-22 07:44:38', NULL, 'COS Demo 2+', 806242, 520, 660, 0, 0, 1, 'LEO (ISS)', 'Falcon 9 + Dragon', 'F9-003', 'Florida SLC-40', 'First night Falcon 9 liftoff, and first private spacecraft to dock with the International Space Station.', '<p><img src="/articleimg/cots2+.jpg" />SpaceX petitioned, and subsequently received approval in July 2011, to merge COTS missions 2 & 3 into one flight where Dragon would both rendezvous and berth simultaneously. Dragon successfully launched aboard the third Falcon 9 flight on 22 May 2012, and managed to complete all mission objectives within three days, becoming the first private spacecraft to berth with the ISS, and it remains the only current servicing spacecraft with the ability to return cargo from the station (up to 3000kg of it). </p>\n\n<p>Following a successful liftoff, first stage separation, and second stage shutoff; Dragon jettisoned its nosecone, separated from the vehicle, and deployed its solar arrays. Over the next three days, Dragon performed a variety of orbital maneuvers, including a lap around the space station, before being grappled with Canadarm2 by astronaut Don Pettit once within the keep out zone of the ISS. </p>\n\n<p>On flight day 5, after evaluating air quality inside the Dragon, the crew opened the hatch and climbed into Dragon for the first time. 520kg of pressurized cargo was transferred to the station, and when the hatched was closed on the last day of flight, contained 660kg of cargo to bring back to Earth. After being unberthed and the grapple of Canadarm2 being released, Dragon backed away from the station, far enough to perform a nine minute long deorbit burn, which landed it 900km off the coast of Baja California in the Pacific. </p> \n\n<p>An unannounced addition to the cargo manifest included a capsule containing the ashes of over 300 people aboard a Celestis payload affixed to the top of the second stage. No other secondary payloads were included. On 23 August 2012, with Dragon successfully completing all requirements, NASA cleared SpaceX to begin operational resupply missions under the Commercial Resupply Services program, ending COTS.</p>\n', 1, 0, 1),
(9, '2012-10-08 00:34:07', NULL, 'SpaceX CRS-1', 1795073, 454, 905, 0, 0, 0, 'LEO (ISS)', 'Falcon 9 + Dragon', 'F9-004', 'Florida SLC-40', 'First of twelve initially contracted International Space Station resupply missions with Dragon. Demonstration of engine out capability. ', '<p><img src="/articleimg/crs-1.jpg" />On 8 October 2012 UTC, SpaceX began its first of twelve (at least) resupply missions to the ISS with the launch of Dragon atop the fourth (and penultimate) Falcon 9 v1.0 rocket. A wet dress rehearsal of the rocket was completed on 31 August, followed by a 29 September static fire. Both of these tests were undertaken without Dragon attached to the vehicle stack. 76 seconds into the mission, engine #1 of the lower stage suffered a loss of pressure, triggering an engine shutdown - debris could be seen in the telescopic video of the launch. Long touted by SpaceX, the vehicle was able to compensate for the reduced performance by burning the remaining 8 engines for a longer length of time, demonstrating for the first time Falcon 9''s unique engine out capability, still managing to insert Dragon into a "flawless" orbit.</p>\n\n<p>Piggybacking along with Dragon uphill was the Orbcomm FM44 satellite as a secondary payload. Due to safety regulations required by NASA to reduce the potential for orbital conflicts between the ISS and similar-inclination objects, a greater than 99% probability is required that the stage will reach their orbital destination. With the loss of the number one engine, and the additional fuel used to compensate for this, the estimate for Orbcomm G2 dropped to 95%. Due to this, SpaceX did not attempt an upper stage restart and Orbcomm FM44 was placed into a low, rapidly-decaying orbit - and was subsequently declared a loss. </p> \n\n<p>Dragon berthed with the ISS on flight day 3, and subsequently 454kg of cargo was unloaded from Dragon to the ISS, and another 905kg was returned. Roughly one sixth of its upmass capability, and one third of its downmass capability. After nearly 18 days attached to the station, Dragon was unberthed and reentered the atmosphere on 28 October 2012. </p> \n', 1, 0, 1),
(10, '2013-03-01 15:10:00', NULL, 'SpaceX CRS-2', 2165040, 677, 1370, 0, 0, 1, 'LEO (ISS)', 'Falcon 9 + Dragon', 'F9-005', 'Florida SLC-40', 'Second contracted flight of Dragon, and the fifth and last flight of Falcon 9 v1.0', '<p><img src="/articleimg/crs-2.jpg" />"Issue with Dragon thruster pods. System inhibiting three of four from initializing. About to command inhibit override." </p>\n\n<p>The second SpaceX cargo resupply mission with Dragon to the International Space Station was launched on the final Falcon 9v1.0 vehicle on 1 March 2013 in a picture-perfect launch with excellent performance from the rocket at 15:10 UTC. The launch was initially delayed due to the investigation into unexpected engine failure on the previous CRS-1 flight. The vehicle was shipped to Cape Canaveral by December 2012, and a static fire occurred on 25 February. </p>\n\n<p>Following a successful launch, problems immediately became apparent with Dragon, mainly involving its propulsion system. The vehicle detected insufficient pressurization of its thruster pods (which are fueled by Nitrogen Tetroxide), causing the flight computers to place the vehicle into a passive abort mode. This disabled its attitude control system and the deployment of the solar arrays. Providing live updates to Twitter as the problem unraveled, Musk mentioned they would attempt to override the system - which succeeded. Once two of the four thruster pods had been activated, the solar arrays deployed. A third thruster pod, followed by the final fourth - was then brought online. Once recovered, the only lasting effect was a delay in berthing the vehicle from 2 December to 3 December. </p>\n\n<p>Dragon carried 677kg of pressurized cargo to the ISS, and took another 1370kg, the largest total transfer so far. Also included was 275kg of unpressurized cargo and another 100kg of mating adapters. This cargo consisted of two Heat Rejection Subsystem Grapple Fixtures (HRSGFs), which are essentially bars to be attached to the ISS radiators to allow for future movement work. This was the first use of Dragon''s trunk. </p>\n\n<p>Dragon stayed berthed to the ISS for over 22 days 18 hours, setting a new Dragon duration record in space. After this, the Falcon 9v1.0 vehicle was retired to make way for the new, more powerful Falcon 9v1.1. </p>\n', 1, 0, 1),
(11, '2013-09-29 16:00:00', NULL, 'CASSIOPE', NULL, NULL, NULL, 0, 1, 6, 'Polar LEO', 'Falcon 9', 'F9-006', 'California SLC-4E', 'First Falcon 9v1.1 launch from Vandenberg delivering CASSIOPE satellite into a polar orbit with a new payload fairing. Attempt at propulsive over-water soft landing. ', '<p><img src="/articleimg/cassiope.jpg" />The mission that could not have gone better. After a stellar day and successful completion of the CASSIOPE mission on 1 September 2013, a relieved Musk commented "It''s being weighing on me quite heavily".</p> \n\n<p>This flight of the 6th Falcon 9 marked many firsts, and held a long list of "precedents and superlatives". These included the 1st Falcon 9v1.1 flight, which has a lengthened lower and upper stage, the new octaweb engine configuration replacing the 3x3 grid configuration, more powerful Merlin 1D engines on the upper and lower stage, a simplified stage separation mechanism, and stronger construction. This is also the 1st Falcon 9 flight to fly with a payload fairing measuring 5.2 metres across, which protected CASSIOPE, an Earth Observation and research satellite for Canada''s MDA corporation and the 4 other secondary payloads from the aerodynamic forces of the atmosphere. Launching from Vandenberg allows Falcon 9 to reach a polar orbit, something not possible from the Cape - both firsts. </p>\n\n<p>Falcon 9v1.1 thundered away from Vandenberg SLC-4E on time, without delay into a cloudless blue California sky and quickly reached supersonic velocities. Stage separation, second stage ignition, and payload fairing separation all occurred as expected. Once orbital velocity was reached, the 500kg CASSIOPE separated. Later in orbit, a restart of the second stage was attempted to demonstrate to future customers the capability to deliver payloads to beyond LEO destinations, but frozen fuel lines prevented the engine restarting. This was thankfully not critical to CASSIOPE''s mission. </p>\n\n<p>After the first stage separated, SpaceX began approaching the problem of reusability from the supersonic end, by relighting three of the Merlin 1D engines to perform the world''s first supersonic retropropulsion burn to turn the stage around and slow it down. This was successful, and as the core descended towards the ocean, the central engine lit for a final time to perform a ''soft landing'' by splashing down. The restart was successful, but a roll began developing, its amplitude large enough to exceed the ability of the roll control thrusters to null it out. Because of this, the fuel centrifuged and the craft splashed down hard into the ocean. Despite this, the test was a complete success.</p>\n', 1, 0, 1),
(12, '2013-12-03 22:41:00', NULL, 'SES-8', NULL, NULL, NULL, 0, 1, 1, 'GTO', 'Falcon 9', 'F9-007', 'Florida SLC-40', 'Second Falcon 9v1.1 launch, first from Cape Canaveral. Other firsts include achieving a GTO orbit, a Merlin 1D upper stage restart, and a communications satellite payload. ', '<p><img src="/articleimg/ses-8.png" />"This launch is very important to the future of SpaceX. This is our toughest mission yet." </p>\n\n<p>SpaceX finally entered the $6.5 billion commercial launch market on 3 December 2013, as the second Falcon 9v1.1, the first launching from Cape Canaveral, rocketed away from the launch pad at dusk to deliver the 3,138kg SES-8 communications satellite into a "super-synchronous" Geostationary Earth Orbit with an apogee of 80,000km. The countdown was plagued with delays which involved two scrubs and many clock resets - despite a Wet Dress Rehearsal + Hot fire combination occurring without issue a few days earlier. This is the first Geostationary satellite for SpaceX, and crucially required the second stage to restart in Low Earth Orbit to deliver the satellite to its desired orbit, something that was unsuccessful on the previous Falcon 9v1.1 flight with CASSIOPE. Frozen fuel lines were to blame, and the issue was fixed by both SES & SpaceX engineers. </p>  \n\n<p>SES'' vote of confidence with using SpaceX as a launch provider was initially perceived as risky at best - yet after the launch, CEO of SES, Martin Halliwell, was quoted as saying "The entry of SpaceX into the commercial market is a game-changer - it is going to really shake the industry to its roots". In response to the successful launch, a day after, Arianespace CEO Stephane Israel stated "I have sent a signal to our customers telling them that I could review our pricing policy, within certain limits". </p>\n\n<p>The upper stage of the Falcon 9 will remain in geostationary transfer orbit, and will decay back into the Earth''s atmosphere within the first half of 2014. </p>\n\n<p>This launch of the Falcon 9v1.1 is the second of three launches required by the Air Force for SpaceX to be considered for defense missions and contracts, potentially allowing them to compete against the current status quo, United Launch Alliance. </p>\n', 1, 0, 1),
(13, '2013-12-20 00:00:00', NULL, 'Thaicom 6', NULL, NULL, NULL, 0, 0, 0, 'GTO', 'Falcon 9', 'F9-008', 'Florida SLC-40', 'Third Falcon 9v1.1 launch, 8th Falcon 9. Will deliver the communications satellite Thaicom 6 into a "super synchronous GRO" orbit similar to SES-8. ', '', 0, 0, NULL),
(14, '2014-02-22 00:00:00', NULL, 'SpaceX CRS-3', NULL, NULL, NULL, 0, 0, 0, 'LEO (ISS)', 'Falcon 9 + Dragon', 'F9-009', 'Florida SLC-40', 'Third Dragon CRS mission to the ISS. First resupply utilizing a Falcon 9v1.1, allowing Dragon to carry a larger capacity of cargo.', '', 0, 0, NULL),
(15, NULL, 'April 2014', 'Asiasat 8', NULL, NULL, NULL, 0, 0, 0, 'GTO', 'Falcon 9', '?', 'Florida SLC-40', '', '', 0, 0, NULL),
(16, '2014-06-06 00:00:00', NULL, 'SpaceX CRS-4', NULL, NULL, NULL, 0, 0, 0, 'LEO (ISS)', 'Falcon 9 + Dragon', '?', 'Florida SLC-40', 'Fourth of twelve Dragon ISS resupply missions, will also include two satellites as part of its secondary payload. ', '', 0, 0, NULL),
(17, NULL, 'Spring 2014', 'Dragon Pad Abort Test', NULL, NULL, NULL, 0, 0, 0, 'Suborbital', 'Falcon 9 + Dragon', '?', 'Florida SLC-40', 'SpaceX will conduct a pad abort of the new upgraded Dragon sitting on top of a stationary Falcon 9 by firing its 8 Superdraco engines to demonstrate pad escape systems as part of its CCiCap contract. ', '', 0, 0, NULL),
(18, NULL, 'Summer 2014', 'Dragon In-flight Abort Test', NULL, NULL, NULL, 0, 0, 0, 'Suborbital', 'Falcon 9 + Dragon', '?', 'Florida SLC-40', 'Dragon will abort from a Falcon 9 mid flight at Max-Q to demonstrate its in flight crew escape system by firing its 8 Superdraco engines before splashing down off the coast of Cape Canaveral. ', '', 0, 0, NULL),
(19, NULL, 'TBD 2014', 'Orbcomm G2 Launch 1', NULL, NULL, NULL, 0, 0, 0, 'LEO', 'Falcon 9', '?', 'Florida SLC-40', 'A Falcon 9 will fly multiple Orbcomm G2 satellites into a Low Earth Orbit as part of a multi-mission contract for the communications corporation.', '', 0, 0, NULL),
(20, NULL, 'TBD 2014', 'SAOCOM 1A', NULL, NULL, NULL, 0, 0, 0, 'Polar LEO', 'Falcon 9', '?', 'California SLC-4E', 'SAOCOM 1A is an Earth observation satellite for the Argentine Space Agency that will be placed into a polar orbit by a Falcon 9 from Vandenberg. ', '', 0, 0, NULL),
(21, NULL, 'TBD 2014', 'SpaceX CRS-5', NULL, NULL, NULL, 0, 0, 0, 'LEO (ISS)', 'Falcon 9 + Dragon', '?', 'Florida SLC-40', 'The fifth CRS mission to the ISS will carry pressurized and unpressurized cargo to the station. Secondary payloads include 2 small satellites.', '', 0, 0, NULL),
(22, NULL, 'TBD 2014', 'SpaceX CRS-6', NULL, NULL, NULL, 0, 0, 0, 'LEO (ISS)', 'Falcon 9 + Dragon', '?', 'Florida SLC-40', 'The sixth of twelve CRS missions will see Dragon again fly to the ISS to deliver and return cargo. ', '', 0, 0, NULL),
(23, NULL, 'TBD 2014', 'Falcon Heavy Test Flight', NULL, NULL, NULL, 0, 0, 0, '?', 'Falcon Heavy', '?', 'California SLC-4E', 'The first Falcon Heavy will lift off from Vandenberg as a demonstration mission. FH enables future mission concepts include a Mars lander and Dragon-around-the-moon-and-back-\nscenarios.', '', 0, 0, NULL);

-- --------------------------------------------------------

--
-- Table structure for table `statistics`
--

CREATE TABLE IF NOT EXISTS `statistics` (
  `stat_id` int(11) NOT NULL AUTO_INCREMENT,
  `stat_name` varchar(100) NOT NULL,
  `value` int(10) NOT NULL,
  `unit` varchar(100) NOT NULL,
  `comment` varchar(1000) NOT NULL,
  PRIMARY KEY (`stat_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=30 ;

--
-- Dumping data for table `statistics`
--

INSERT INTO `statistics` (`stat_id`, `stat_name`, `value`, `unit`, `comment`) VALUES
(1, 'Launch Count', 12, 'Launches', 'As of December 2013, SpaceX has launched 12 rockets (all from it''s sole rocket family, Falcon) to a variety of destinations, from LEO to the ISS to GEO; carrying scientific and commercial payloads along with Dragon under its commercial resupply contract with NASA.'),
(2, 'Falcon 9 Launch Count', 7, 'Launches', 'Falcon 9 is SpaceX''s workhorse of the Falcon fleet, able to carry 13,150kg to LEO & 4,850kg to GTO. To date, it has launched on 7 occasions, predominantly lifting communications satellites and Dragon to the ISS. Designed to be thin enough to be carried on a flatbed truck; the pencil thin Falcon 9 at 3.7m wide is taller than the entire Space Shuttle stack, yet thinner than a Shuttle solid rocket booster.'),
(3, 'FH Launch Count', 0, 'Launches', 'Falcon Heavy is the world''s most powerful rocket, pushing 4 million pounds of thrust (17.6MN) at liftoff, and is able to haul 53 metric tons to LEO - the equivalent of a fully loaded Boeing 737. Only the Saturn V has delivered more payload to orbit, yet it is the third of the cost of a Delta IV Heavy and has twice the performance. SpaceX is gearing up for the first flight of Falcon Heavy in 2014.'),
(4, 'Falcon 1 Launch Count', 5, 'Launches', 'Falcon 1, now retired, was SpaceX''s original two stage rocket equipped with a single Merlin 1C engine - able to lift 670kg to LEO. Launched exclusively from Kwajalein, it was used for 5 flights, of which the first 3 failed. At the time of the first successful flight of Falcon 1 (flight 4), SpaceX was on the verge of bankruptcy. '),
(5, 'Dragon Missions', 4, 'Missions', 'Dragon - SpaceX''s orbital spacecraft - has flown into space 4 times atop of a Falcon 9 rocket. On completion of its first mission in December 2010, Dragon became the first privately developed spacecraft to be successfully recovered from orbit. If required, Dragon can also be placed on top of Falcon Heavy. Future variants of Dragon are designed to carry crew and return propulsively to the launch site. '),
(6, 'ISS Resupplies', 2, 'Resupplies', 'Under NASA''s Commercial Resupply Services program, Dragon regularly lifts cargo to and returns cargo from the ISS as part of a 12-mission contract. SpaceX''s valued contract contains both more missions at a cheaper price than a similar contract awarded to Orbital Sciences. As of January 2014, 2 of these missions have been completed.'),
(7, 'Dragon Time in Space', 4778347, '', 'Dragon''s missions have become progressively longer during each flight. The first test flight of Dragon lasted just over 3 hours, while the most recent flight, CRS-2, ended up with a mission elapsed time in excess of 25 days. Dragon''s total on-orbit endurance however is up to 2 years. The next Dragon flight (CRS-3) is scheduled for February 2014.'),
(8, 'Launches from Florida', 6, 'Launches', 'Florida, specifically, Cape Canaveral Air Force Station Space Launch Complex 40 (SLC-40), is the launch site of Falcon 9 carrying Dragon towards the International Space Station, and the starting point for satellites heading into Geostationary Earth Orbit.'),
(9, 'Launches from California', 1, 'Launch', 'Vandenberg AFB Space Launch Complex 4E (SLC-4E) in California is SpaceX''s departure point for satellites (mostly scientific and Earth observation) seeking a polar orbit around the Earth. SLC-4E was last used in 2005 for the final flight of the Titan IV rocket.'),
(10, 'Launches from Kwajalein', 5, 'Launches', 'Omelek Island within the Kwajalein Atoll was SpaceX''s first launch site and used exclusively to launch the Faclon 1. Far from other land, Kwajalein is surrounded by vast amounts of sea and open ocean, making it the perfect site to launch rockets. Ironically, this climate also led to the failure of the first Falcon 1 launch, during which the engine failed 25 seconds into flight due to a corroded bolt.'),
(11, 'Merlin 1D Operating Time', 2988, 'Seconds', 'Merlin 1D is the 4th iteration of SpaceX''s Merlin engine family. Using a mixture of RP-1 (Kerosene) and Liquid Oxygen (LOX), it achieves a thrust to weight ratio exceeding 150, the highest of any kerolox engine. It delivers 654 kN (147,000 lbs) of thrust with a specific impulse of 282 seconds at sea level, and 716 kN (161,000 lbs) of thrust with a specific impulse of 311 seconds in a vacuum. After the second Falcon 9 v1.1 flight, Elon Musk announced that Merlin 1D was actually operating at 85% of its potential, and anticipated to be able to increase the sea level thrust to 730 kN (165,000 lbs).'),
(12, 'Merlin 1D Successes', 18, 'Percent', 'To date, no Merlin 1D engine has ever failed in flight, yielding a perfect 100% success rate with 18 engines. Up to 2 Merlin 1D engines can fail on board Falcon 9''s first stage, and Falcon 9 can still successfully complete a mission.'),
(13, 'Merlin 1D Failures', 0, 'Percent', ''),
(14, 'Astronauts - Current', 0, 'Astronauts', 'No SpaceX astronauts are in orbit at this time. Currently, SpaceX is actively persuing a human spaceflight program which will begin with a Dragon pad abort test in Spring 2014, followed by a Dragon in-flight abort test aboard a Falcon 9 in Summer 2014. Completion of these milestones under NASA''s Commercial Crew program will allow SpaceX to fly its first astronauts in 2016, and to the ISS in 2017.'),
(15, 'Astronauts - Cumulative', 0, 'Astronauts', 'Currently, SpaceX is actively perusing a human spaceflight program which will begin with a Dragon pad abort test in Spring 2014, followed by a Dragon in-flight abort test aboard a Falcon 9 in Summer 2014. The crewed version of Dragon, named DragonRider, will be able to carry up to 7 astronauts.'),
(16, 'Satellites Launched', 23, 'Satellites', 'Over the course of 12 Falcon 9 & Falcon 1 missions, SpaceX has launched 23 satellites into Earth orbit, both successfully and unsuccessfully. The majority of these are nanosatellites and cubesats. In fact, on the Falcon 9 COTS 1 mission which lofted Dragon into the orbit for the first time, SpaceX deployed an additional 8 satellites. A close second is the inaugural launch of Falcon 9 v1.1 which lofted CASSIOPE into orbit along with 5 other secondary payloads.'),
(17, 'Primary Satellites Launched', 2, 'Satellites', 'SpaceX has launched two primary payloads with large masses, both on Falcon 9 v1.1 vehicles. These are CASSIOPE & SES-8, which weigh 500kg & 3,138kg respectively. The former is a scientific and technology experiment mission for MDA Corporation of Canada and the latter is a communications satellite for SES World Skies. '),
(18, 'Grasshopper Flights', 8, 'Flights', 'Grasshopper is an experimental vertical-takeoff vertical-landing suborbital rocket that SpaceX is using to test and develop the technologies needed to successfully return a Falcon rocket back to the launch site propulsively after separation; and consists of a Falcon 9 lower stage body and a single Merlin 1D engine. As of December 2013, it has made 8 flights, up to a height of 744 metres, with one flight including a 100m lateral diversion. It expected to be replaced by ''F9R'' which extends Grasshoppers flight profile into the transonic and supersonic regimes.'),
(19, 'Distance', 79130, 'Kilometres', 'On 3 December 2013, SpaceX hardware achieved its farthest distance from Earth ever when SES-8 and the Falcon 9 upper stage were boosted in a super-synchronous Geostationary Transfer Orbit around the Earth with an apogee of nearly 80,000km. \n'),
(20, 'Vehicles Landed', 0, 'Landed', 'Beginning in late-2014, SpaceX hopes for the first time ever to bring the lower stage of the Falcon 9 launch vehicle back to a landing site propulsively under its own power. Rapid reuse of rocket stages will reduce the cost of access to orbit. Dragon 2 will also land propulsively after returning from orbit. Eventually, SpaceX also hopes to return the upper stage of the Falcon 9 & Falcon Heavy back to a landing pad.'),
(21, 'SpaceX vs. ULA - 2014, SpaceX', 0, 'Launches', ''),
(22, 'SpaceX vs. ULA - 2014, ULA', 0, 'Launches', ''),
(23, 'SpaceX vs. ULA - 2013, SpaceX', 3, 'Launches', ''),
(24, 'SpaceX vs. ULA - 2013, ULA', 11, 'Launches', ''),
(25, 'SpaceX vs. ULA - 2012, SpaceX', 2, 'Launches', ''),
(26, 'SpaceX vs. ULA - 2012, ULA', 10, 'Launches', ''),
(27, 'SpaceX vs. ULA - All Time, SpaceX', 12, 'Launches', ''),
(28, 'SpaceX vs. ULA - All Time, ULA', 77, 'Launches', ''),
(29, 'Quickest Turnaround', 4909260, 'seconds', 'The time between Falcon 1 flights 3 & 4 in late 2008 set a record that remains to this day the quickest turnaround time between two SpaceX launches.');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
